import type { ResourceCardProps } from "@/components/resource-card"

export const resourcesData: ResourceCardProps[] = [
  {
    id: "1",
    title: "New Migration Patterns Discovered in Blue Whales",
    date: "May 2, 2025",
    category: "Research",
    excerpt:
      "Researchers have identified previously unknown migration routes for blue whales in the Pacific Ocean, providing new insights into their behavior and adaptation to changing ocean conditions.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Blue+Whale+Research",
    readTime: "8 min read",
    author: "Dr. Emily Chen",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=EC",
    featured: true,
  },
  {
    id: "2",
    title: "Ocean Acidification Effects on Coral Reefs",
    date: "April 28, 2025",
    category: "Research",
    excerpt:
      "A comprehensive study reveals the accelerating impact of ocean acidification on coral reef ecosystems worldwide, with concerning implications for marine biodiversity.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Coral+Research",
    readTime: "12 min read",
    author: "Prof. James Wilson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=JW",
  },
  {
    id: "3",
    title: "Deep Sea Exploration Yields New Species",
    date: "April 15, 2025",
    category: "Discovery",
    excerpt:
      "Marine biologists have identified 12 new species during a deep-sea expedition in the Mariana Trench, highlighting how much remains unknown about our ocean depths.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Deep+Sea+Research",
    readTime: "10 min read",
    author: "Dr. Sarah Johnson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=SJ",
  },
  {
    id: "4",
    title: "Marine Protected Areas Show Positive Results",
    date: "May 5, 2025",
    category: "Conservation",
    excerpt:
      "A 10-year study of marine protected areas shows significant recovery of fish populations and ecosystem health, providing evidence for expanded conservation efforts.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Marine+Protected+Areas",
    readTime: "7 min read",
    author: "Maria Rodriguez",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MR",
    featured: true,
  },
  {
    id: "5",
    title: "International Agreement on Plastic Pollution",
    date: "April 22, 2025",
    category: "Conservation",
    excerpt:
      "World leaders have signed a landmark agreement to reduce plastic waste entering the oceans by 80% by 2030, marking a significant step in marine conservation.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Plastic+Pollution",
    readTime: "9 min read",
    author: "Thomas Lee",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=TL",
  },
  {
    id: "6",
    title: "Community-Led Conservation Success Story",
    date: "April 10, 2025",
    category: "Conservation",
    excerpt:
      "Local communities in coastal regions have successfully implemented sustainable fishing practices, leading to marine ecosystem recovery and improved livelihoods.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Community+Conservation",
    readTime: "6 min read",
    author: "Aisha Patel",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AP",
  },
  {
    id: "7",
    title: "Rare Megamouth Shark Sighted",
    date: "May 7, 2025",
    category: "Discovery",
    excerpt:
      "Scientists have documented a rare sighting of the elusive megamouth shark off the coast of Japan, providing valuable data about this mysterious deep-sea species.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Megamouth+Shark",
    readTime: "5 min read",
    author: "Dr. Kenji Tanaka",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=KT",
  },
  {
    id: "8",
    title: "New Coral Reef Discovered in Deep Waters",
    date: "April 25, 2025",
    category: "Discovery",
    excerpt:
      "Researchers have found a previously unknown coral reef system thriving at unusual depths in the Indian Ocean, challenging our understanding of coral ecosystems.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Deep+Coral+Reef",
    readTime: "8 min read",
    author: "Dr. Amara Singh",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AS",
  },
  {
    id: "9",
    title: "Ancient Shipwreck Reveals Marine Ecosystem",
    date: "April 18, 2025",
    category: "Discovery",
    excerpt:
      "A 400-year-old shipwreck has become a thriving artificial reef, hosting dozens of marine species and providing insights into ecosystem development.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Shipwreck+Ecosystem",
    readTime: "7 min read",
    author: "Marco Rossi",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MR",
  },
  {
    id: "10",
    title: "Climate Change Impact on Marine Mammals",
    date: "May 1, 2025",
    category: "Research",
    excerpt:
      "New research documents how climate change is affecting marine mammal populations worldwide, with particular focus on Arctic species and their changing habitats.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Climate+Change+Impact",
    readTime: "11 min read",
    author: "Dr. Lisa Nordstrom",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=LN",
  },
  {
    id: "11",
    title: "Innovative Technologies for Ocean Cleanup",
    date: "April 20, 2025",
    category: "Conservation",
    excerpt:
      "Engineers have developed new autonomous systems for removing plastic waste from oceans, with pilot programs showing promising results in heavily polluted areas.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Ocean+Cleanup",
    readTime: "9 min read",
    author: "Michael Zhang",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MZ",
  },
  {
    id: "12",
    title: "Marine Biology Education Programs for Schools",
    date: "April 5, 2025",
    category: "Education",
    excerpt:
      "New curriculum resources are helping K-12 students learn about marine ecosystems and conservation through interactive, hands-on activities.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Marine+Education",
    readTime: "6 min read",
    author: "Emma Thompson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=ET",
  },
  // Adding documentaries
  {
    id: "13",
    title: "Blue Planet II: The Deep",
    date: "March 15, 2025",
    category: "Documentary",
    excerpt:
      "An exploration of the deepest parts of our oceans, revealing extraordinary creatures and behaviors never before filmed, narrated by Sir David Attenborough.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Blue+Planet+II",
    readTime: "58 min watch",
    author: "BBC Earth",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=BBC",
    featured: true,
  },
  {
    id: "14",
    title: "Chasing Coral: The Vanishing Reefs",
    date: "March 10, 2025",
    category: "Documentary",
    excerpt:
      "A team of divers, photographers, and scientists set out on an ocean adventure to discover why coral reefs are disappearing at an unprecedented rate.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Chasing+Coral",
    readTime: "93 min watch",
    author: "Exposure Labs",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=EL",
  },
  {
    id: "15",
    title: "Mission Blue: Hope Spots",
    date: "February 28, 2025",
    category: "Documentary",
    excerpt:
      "Dr. Sylvia Earle's mission to create a global network of marine protected areas, called 'Hope Spots,' to safeguard the health of our oceans.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Mission+Blue",
    readTime: "95 min watch",
    author: "Netflix Originals",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=NF",
  },
  {
    id: "16",
    title: "Seaspiracy: Fishing Industry Exposed",
    date: "February 15, 2025",
    category: "Documentary",
    excerpt:
      "An investigation into the environmental impact of industrial fishing and the human rights abuses in the fishing industry worldwide.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Seaspiracy",
    readTime: "89 min watch",
    author: "Ali Tabrizi",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AT",
  },
  {
    id: "17",
    title: "My Octopus Teacher",
    date: "January 25, 2025",
    category: "Documentary",
    excerpt:
      "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Octopus+Teacher",
    readTime: "85 min watch",
    author: "Craig Foster",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CF",
  },
  {
    id: "18",
    title: "A Plastic Ocean: The Truth About Pollution",
    date: "January 10, 2025",
    category: "Documentary",
    excerpt:
      "An adventure documentary that brings to light the consequences of our global disposable lifestyle, revealing the causes and solutions for plastic pollution.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Plastic+Ocean",
    readTime: "102 min watch",
    author: "Plastic Oceans Foundation",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=PO",
  },
  // Additional research articles
  {
    id: "19",
    title: "Acoustic Monitoring of Whale Populations",
    date: "May 10, 2025",
    category: "Research",
    excerpt:
      "New acoustic monitoring technologies are revolutionizing how scientists track and study whale populations, providing non-invasive methods for conservation research.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Acoustic+Monitoring",
    readTime: "14 min read",
    author: "Dr. Carlos Mendez",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CM",
  },
  {
    id: "20",
    title: "Microplastics in Marine Food Webs",
    date: "April 30, 2025",
    category: "Research",
    excerpt:
      "A comprehensive study on how microplastics enter and move through marine food webs, with implications for both wildlife and human health.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Microplastics",
    readTime: "15 min read",
    author: "Dr. Hannah Kim",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=HK",
  },
  // Additional conservation articles
  {
    id: "21",
    title: "Seagrass Restoration Projects Worldwide",
    date: "March 25, 2025",
    category: "Conservation",
    excerpt:
      "An overview of successful seagrass meadow restoration projects that are helping to rebuild critical marine habitats and sequester carbon.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Seagrass+Restoration",
    readTime: "8 min read",
    author: "Dr. Robert Green",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=RG",
  },
  {
    id: "22",
    title: "Indigenous Knowledge in Marine Conservation",
    date: "March 20, 2025",
    category: "Conservation",
    excerpt:
      "How traditional ecological knowledge from indigenous communities is being integrated with scientific approaches to enhance marine conservation efforts.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Indigenous+Knowledge",
    readTime: "11 min read",
    author: "Maya Williams",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MW",
  },
  // Additional educational resources
  {
    id: "23",
    title: "Virtual Reality Ocean Exploration for Classrooms",
    date: "February 5, 2025",
    category: "Education",
    excerpt:
      "New VR technologies are bringing ocean exploration into classrooms, allowing students to experience marine environments without leaving school.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=VR+Ocean",
    readTime: "7 min read",
    author: "Tech Education Team",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=TET",
  },
  {
    id: "24",
    title: "Citizen Science Programs for Ocean Monitoring",
    date: "January 15, 2025",
    category: "Education",
    excerpt:
      "How everyday citizens are contributing to marine research through organized monitoring programs, with opportunities for public participation.",
    imageUrl: "/placeholder.svg?height=400&width=600&text=Citizen+Science",
    readTime: "9 min read",
    author: "Community Science Initiative",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CSI",
  },
]

export type ResourceCategory = "All" | "Research" | "Conservation" | "Discovery" | "Documentary" | "Education"
