import type { ResourceCardProps } from "@/components/resource-card"

export const resourcesData: ResourceCardProps[] = [
  {
    id: "1",
    title: "New Migration Patterns Discovered in Blue Whales",
    date: "May 2, 2025",
    category: "Research",
    excerpt:
      "Researchers have identified previously unknown migration routes for blue whales in the Pacific Ocean, providing new insights into their behavior and adaptation to changing ocean conditions.",
    imageUrl: "https://www.oceanactionhub.org/storage/2023/10/blue-whale-mother-and-calf-.jpg",
    readTime: "8 min read",
    author: "Dr. Emily Chen",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=EC",
    featured: true,
  },
  {
    id: "2",
    title: "Ocean Acidification Effects on Coral Reefs",
    date: "April 28, 2025",
    category: "Research",
    excerpt:
      "A comprehensive study reveals the accelerating impact of ocean acidification on coral reef ecosystems worldwide, with concerning implications for marine biodiversity.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLsNFfZLR9Bt9sZSoRwy0VotL7DOILKXbohVnIyEh1m7pWDO_eG3IMpeDu6TldO5Kak_8&usqp=CAU",
    readTime: "12 min read",
    author: "Prof. James Wilson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=JW",
  },
  {
    id: "3",
    title: "Deep Sea Exploration Yields New Species",
    date: "April 15, 2025",
    category: "Discovery",
    excerpt:
      "Marine biologists have identified 12 new species during a deep-sea expedition in the Mariana Trench, highlighting how much remains unknown about our ocean depths.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk9U9uikL-Q3VO09skqxYq8e8DihVdRZ1mwQ&s",
    readTime: "10 min read",
    author: "Dr. Sarah Johnson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=SJ",
  },
  {
    id: "4",
    title: "Marine Protected Areas Show Positive Results",
    date: "May 5, 2025",
    category: "Conservation",
    excerpt:
      "A 10-year study of marine protected areas shows significant recovery of fish populations and ecosystem health, providing evidence for expanded conservation efforts.",
    imageUrl: "https://www.scuba.com/blog/wp-content/uploads/2020/04/shutterstock_295429772-825x465.jpg",
    readTime: "7 min read",
    author: "Maria Rodriguez",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MR",
    featured: true,
  },
  {
    id: "5",
    title: "International Agreement on Plastic Pollution",
    date: "April 22, 2025",
    category: "Conservation",
    excerpt:
      "World leaders have signed a landmark agreement to reduce plastic waste entering the oceans by 80% by 2030, marking a significant step in marine conservation.",
    imageUrl: "https://www.reusethisbag.com/wp-content/uploads/2021/08/ocean-pollution-plastics.jpg.webp",
    readTime: "9 min read",
    author: "Thomas Lee",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=TL",
  },
  {
    id: "6",
    title: "Community-Led Conservation Success Story",
    date: "April 10, 2025",
    category: "Conservation",
    excerpt:
      "Local communities in coastal regions have successfully implemented sustainable fishing practices, leading to marine ecosystem recovery and improved livelihoods.",
    imageUrl: "https://www.greenpeace.org/static/planet4-malaysia-stateless/2024/06/2a90d588-gp0stzng2-1024x683.jpg",
    readTime: "6 min read",
    author: "Aisha Patel",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AP",
  },
  {
    id: "7",
    title: "Rare Megamouth Shark Sighted",
    date: "May 7, 2025",
    category: "Discovery",
    excerpt:
      "Scientists have documented a rare sighting of the elusive megamouth shark off the coast of Japan, providing valuable data about this mysterious deep-sea species.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4TB0usukysz82fPIPpOI16hhaaF0XqItZDw&s",
    readTime: "5 min read",
    author: "Dr. Kenji Tanaka",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=KT",
  },
  {
    id: "8",
    title: "New Coral Reef Discovered in Deep Waters",
    date: "April 25, 2025",
    category: "Discovery",
    excerpt:
      "Researchers have found a previously unknown coral reef system thriving at unusual depths in the Indian Ocean, challenging our understanding of coral ecosystems.",
    imageUrl: "https://t4.ftcdn.net/jpg/02/78/12/73/360_F_278127372_mWGRfu0XaAaJbrGCCo4b4WHLaXU4U3p7.jpg",
    readTime: "8 min read",
    author: "Dr. Amara Singh",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AS",
  },
  {
    id: "9",
    title: "Ancient Shipwreck Reveals Marine Ecosystem",
    date: "April 18, 2025",
    category: "Discovery",
    excerpt:
      "A 400-year-old shipwreck has become a thriving artificial reef, hosting dozens of marine species and providing insights into ecosystem development.",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/v2/t:0,l:0,cw:1920,ch:1080,q:80,w:1920/yGRJauEXsS9Qfe9FaFWW76.jpg",
    readTime: "7 min read",
    author: "Marco Rossi",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MR",
  },
  {
    id: "10",
    title: "Climate Change Impact on Marine Mammals",
    date: "May 1, 2025",
    category: "Research",
    excerpt:
      "New research documents how climate change is affecting marine mammal populations worldwide, with particular focus on Arctic species and their changing habitats.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFbnzC-9yVmDF-dBcfwT2TJlN4N2lZWXGYug&s",
    readTime: "11 min read",
    author: "Dr. Lisa Nordstrom",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=LN",
  },
  {
    id: "11",
    title: "Innovative Technologies for Ocean Cleanup",
    date: "April 20, 2025",
    category: "Conservation",
    excerpt:
      "Engineers have developed new autonomous systems for removing plastic waste from oceans, with pilot programs showing promising results in heavily polluted areas.",
    imageUrl: "https://i.insider.com/61673f4b38c19600182fbf98?width=700",
    readTime: "9 min read",
    author: "Michael Zhang",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MZ",
  },
  {
    id: "12",
    title: "Marine Biology Education Programs for Schools",
    date: "April 5, 2025",
    category: "Education",
    excerpt:
      "New curriculum resources are helping K-12 students learn about marine ecosystems and conservation through interactive, hands-on activities.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEhV4am6DUn56Sit6CMtGaaAhSQTzN3NYruw&s",
    readTime: "6 min read",
    author: "Emma Thompson",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=ET",
  },
  // Adding documentaries
  {
    id: "13",
    title: "Blue Planet II: The Deep",
    date: "March 15, 2025",
    category: "Documentary",
    excerpt:
      "An exploration of the deepest parts of our oceans, revealing extraordinary creatures and behaviors never before filmed, narrated by Sir David Attenborough.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGHp4H4zbdLNjgSC8GIbYKm08KXATB6PEgLQ&s",
    readTime: "58 min watch",
    author: "BBC Earth",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=BBC",
    featured: true,
  },
  {
    id: "14",
    title: "Chasing Coral: The Vanishing Reefs",
    date: "March 10, 2025",
    category: "Documentary",
    excerpt:
      "A team of divers, photographers, and scientists set out on an ocean adventure to discover why coral reefs are disappearing at an unprecedented rate.",
    imageUrl: "https://resizing.flixster.com/ORuQChAss6Uf0iz_GS7gsXuSNlU=/fit-in/705x460/v2/https://resizing.flixster.com/Tl6FWuz3ycpS2GZsAfd3IucFMeg=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzY4ZjJhYmVhLWU3ODgtNDZkNi1iMWE5LTM0NDgwYTE4MTA4ZC53ZWJw",
    readTime: "93 min watch",
    author: "Exposure Labs",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=EL",
  },
  {
    id: "15",
    title: "Mission Blue: Hope Spots",
    date: "February 28, 2025",
    category: "Documentary",
    excerpt:
      "Dr. Sylvia Earle's mission to create a global network of marine protected areas, called 'Hope Spots,' to safeguard the health of our oceans.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-JnGBDN3rbbxFITe7fe3vqH5S4NCOcm4E7EQYTwYN6XYhSyDNLoGuacTcU_9HBWOxpzE&usqp=CAU",
    readTime: "95 min watch",
    author: "Netflix Originals",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=NF",
  },
  {
    id: "16",
    title: "Seaspiracy: Fishing Industry Exposed",
    date: "February 15, 2025",
    category: "Documentary",
    excerpt:
      "An investigation into the environmental impact of industrial fishing and the human rights abuses in the fishing industry worldwide.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkS5WLUungqhVosuWQQZCRUTzgOuh0N0Xp0g&s",
    readTime: "89 min watch",
    author: "Ali Tabrizi",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=AT",
  },
  {
    id: "17",
    title: "My Octopus Teacher",
    date: "January 25, 2025",
    category: "Documentary",
    excerpt:
      "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.",
    imageUrl: "https://images.theconversation.com/files/443875/original/file-20220201-25-lb03xa.jpg?ixlib=rb-1.1.0&rect=0%2C0%2C4747%2C3172&q=45&auto=format&w=754&fit=cliphttps://octonation.com/wp-content/uploads/2021/10/craig-with-common-octopus-scaled.jpeg",
    readTime: "85 min watch",
    author: "Craig Foster",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CF",
  },
  {
    id: "18",
    title: "A Plastic Ocean: The Truth About Pollution",
    date: "January 10, 2025",
    category: "Documentary",
    excerpt:
      "An adventure documentary that brings to light the consequences of our global disposable lifestyle, revealing the causes and solutions for plastic pollution.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5vyNchNCvTxnkyruD0nEhnAobqI8eRGx4eg&s",
    readTime: "102 min watch",
    author: "Plastic Oceans Foundation",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=PO",
  },
  // Additional research articles
  {
    id: "19",
    title: "Acoustic Monitoring of Whale Populations",
    date: "May 10, 2025",
    category: "Research",
    excerpt:
      "New acoustic monitoring technologies are revolutionizing how scientists track and study whale populations, providing non-invasive methods for conservation research.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3AumXQzQzyxCWRIHafPuesKkIfwy90tw4pg&s",
    readTime: "14 min read",
    author: "Dr. Carlos Mendez",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CM",
  },
  {
    id: "20",
    title: "Microplastics in Marine Food Webs",
    date: "April 30, 2025",
    category: "Research",
    excerpt:
      "A comprehensive study on how microplastics enter and move through marine food webs, with implications for both wildlife and human health.",
    imageUrl: "https://www.digicomply.com/hubfs/Microplastics.jpg",
    readTime: "15 min read",
    author: "Dr. Hannah Kim",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=HK",
  },
  // Additional conservation articles
  {
    id: "21",
    title: "Seagrass Restoration Projects Worldwide",
    date: "March 25, 2025",
    category: "Conservation",
    excerpt:
      "An overview of successful seagrass meadow restoration projects that are helping to rebuild critical marine habitats and sequester carbon.",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj5n6ABwBJFHM1dgW0dxpJnNT4nvv7o2noAQ&s",
    readTime: "8 min read",
    author: "Dr. Robert Green",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=RG",
  },
  {
    id: "22",
    title: "Indigenous Knowledge in Marine Conservation",
    date: "March 20, 2025",
    category: "Conservation",
    excerpt:
      "How traditional ecological knowledge from indigenous communities is being integrated with scientific approaches to enhance marine conservation efforts.",
    imageUrl: "https://images.theconversation.com/files/404958/original/file-20210607-134455-5eowi7.jpg?ixlib=rb-4.1.0&rect=44%2C692%2C4918%2C2455&q=45&auto=format&w=1356&h=668&fit=crop",
    readTime: "11 min read",
    author: "Maya Williams",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=MW",
  },
  // Additional educational resources
  {
    id: "23",
    title: "Virtual Reality Ocean Exploration for Classrooms",
    date: "February 5, 2025",
    category: "Education",
    excerpt:
      "New VR technologies are bringing ocean exploration into classrooms, allowing students to experience marine environments without leaving school.",
    imageUrl: "https://www.marinebiodiversity.ca/wp-content/uploads/2025/05/virtual-marine-biology-classroom.jpg",
    readTime: "9 min read",
    author: "Community Science Initiative",
    authorAvatar: "/placeholder.svg?height=100&width=100&text=CSI",
  },
]

export type ResourceCategory = "All" | "Research" | "Conservation" | "Discovery" | "Documentary" | "Education"
